lib: Assign explicit pointer-type to todo!()-initialized device
With the current constructor casting to c_void the compiler has no way
of deducing the type when only functions are called on the
`todo!()`-initialized `device`.  this complements
https://github.com/Traverse-Research/gpu-allocator/pull/64 by solving:

    ---- src\lib.rs - (line 93) stdout ----
    error[E0282]: type annotations needed
    Error:   --> src\lib.rs:131:5
       |
    9  | let device = todo!();
       |     ------ consider giving `device` a type
    ...
    40 |     device.as_ref().unwrap().CreatePlacedResource(
       |     ^^^^^^ cannot infer type
       |
       = note: type must be known at this point